# /home/ateebamateen/.config/libinput-gestures.conf

# #-------------------SWIPE_VERTICAL GESTURES--------------------
# # 3-finger swipe down to bring down dropdown terminal (F12)
# gesture swipe down 3 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 88:1 88:0'
# # 3-finger swipe up to peek at desktop (Win + X)
# gesture swipe up 3 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 125:1 45:1 45:0 125:0'


# # (these two below are taken by default KDE shortcuts anyway)
# # 4-finger swipe down gesture
# # gesture swipe down 4 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 88:1 88:0'
# # 4-finger swipe up gesture
# # gesture swipe up 4 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 88:1 88:0'



# #-------------------SWIPE_HORIZONTAL GESTURES--------------------
# # 3‑finger swipe right → Meta + A
# gesture swipe right 3 bash -c 'YDOTOOL_SOCKET="$HOME/.ydotool_socket" /usr/bin/ydotool key 125:1 30:1 30:0 125:0'

# # 3‑finger swipe left → Meta + D
# gesture swipe left 3 bash -c 'YDOTOOL_SOCKET="$HOME/.ydotool_socket" /usr/bin/ydotool key 125:1 32:1 32:0 125:0'


# 4-finger swipe right to cycle through windows (Ctrl+Tab)

gesture swipe right 4 bash -c 'sleep 0.1 && YDOTOOL_SOCKET=/home/ateebamateen/.ydotool_socket /usr/bin/ydotool key 29:1 104:1 104:0 29:0'
gesture swipe left 4 bash -c 'sleep 0.1 && YDOTOOL_SOCKET=/home/ateebamateen/.ydotool_socket /usr/bin/ydotool key 29:1 109:1 109:0 29:0'

# #-------------------''''''''PINCHING GESTURES--------------------
# #3-finger pinch in gesture to close windows (alt+f4)

gesture pinch in 3 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" niri msg action close-window'
# # 3-finger pinch out to show apps
gesture pinch out 3 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket"  dms ipc call spotlight toggle'


# # 4-finger pinch in gesture for closing tabs (Ctrl+W)
# gesture pinch in 4 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 29:1 17:1 17:0 29:0'
# # 4-finger pinch out gesture for showing lock screen (WIN + L)
# gesture pinch out 4 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key 125:1 38:1 38:0 125:0'


# #3-finger pinch clockwise gesture (not set)
# # gesture pinch clockwise bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key []'
# #3-finger pinch counterclockwise gesture (not set)
# # gesture pinch counterclockwise bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key []'



# #-------------------HOLD GESTURES--------------------
# # 3-finger tap
# # gesture hold on 3 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key []'
# # gesture hold on 4 bash -c 'YDOTOOL_SOCKET="/home/ateebamateen/.ydotool_socket" /usr/bin/ydotool key []'
